- name: show facts
  hosts: all
  become: yes
  tasks:
    - name: Uninstall Apache on RedHat-based Systems
      yum:
        name: httpd
        state: absent
      when: ansible_os_family == "RedHat"
