- name: show facts
  hosts: all
  become: yes
  tasks:
    - name: Install Apache on RedHat-based Systems
      yum:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"
