---
- name: Gather Facts from EC2 Instance
  hosts: webserver
  gather_facts: yes
  tasks:
    - name: Print all gathered facts
      debug:
        var: ansible_facts
# ---
# - name: Gather Facts Example
#   hosts: all
#   tasks:
#     - name: Print out the OS family
#       debug:
#         msg: 'The OS family is {{ ansible_os_family }}'
